version: '3'

services:
  www:
    build: docker/php
    container_name: ipamcraft
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
