version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/symfony
    environment:
      APP_ENV: prod
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
    networks:
      - symfony-net

  #db:
  #  image: mariadb:10.11
  #  container_name: mariadb
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: symfony
  #    MYSQL_USER: symfony
  #    MYSQL_PASSWORD: symfony
  #  volumes:
  #    - db_data:/var/lib/mysql
  #  ports:
  #    - "3306:3306"
  #  networks:
  #    - symfony-net

  web:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - symfony-net

volumes:
  db_data:

networks:
  symfony-net:
